#!/usr/bin/env zsh
# vim: filetype=sh
#───────────────────────────────────────────────────────────────────────────────

# INFO block commit if there are any issues reported
set -o errexit

echo "Pre-Commit Hook"

echo "(1/3) Biome"
npx biome check --apply --log-kind="compact" "$(git rev-parse --show-toplevel)"

echo "(2/3) TypeScript"
npx tsc --noEmit --skipLibCheck --strict
echo "Done."

echo "(3/3) Markdownlint"
npx markdownlint --ignore="node_modules" "$(git rev-parse --show-toplevel)"
echo "Done."
echo
