# yamllint disable rule:truthy
#───────────────────────────────────────────────────────────────────────────────
extends: 
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
plugins: ["@typescript-eslint"]
root: true # stop annoying deprecation warning
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2021
  sourceType: module

#───────────────────────────────────────────────────────────────────────────────
rules:

  # TypeScript specific
  "@typescript-eslint/no-unused-vars": off
  "@typescript-eslint/ban-ts-comment": 
    - warn
    - ts-ignore: allow-with-description
      ts-expect-error: allow-with-description
  "@typescript-eslint/no-extra-semi": warn
  "@typescript-eslint/no-empty-function": warn
  no-unused-vars: warn
  require-await: off # errors for `async onload`, still have to figure out how to fix

  # code structure
  complexity: [error, 13]
  max-depth: [error, 4]

  # variables
  no-shadow:
    - error
    - builtinGlobals: true
      hoist: all
  camelcase:
    - warn
    - properties: always
      ignoreImports: true
  no-var: error
  prefer-const: warn
  sort-vars: warn
  no-use-before-define: error
  no-multi-assign: error
  no-sequences: error
  no-undefined: error
  one-var-declaration-per-line:
    - error
    - initializations

  # spaces
  no-mixed-spaces-and-tabs: warn
  indent:
    - warn
    - tab
    - SwitchCase: 1
  no-multi-spaces: warn
  array-bracket-spacing: warn
  space-before-blocks: warn
  semi-spacing: warn
  object-curly-spacing:
    - warn
    - always
  no-whitespace-before-property: error
  no-empty: warn
  arrow-spacing: warn
  keyword-spacing: warn
  spaced-comment:
    - warn
    - always
    - exceptions: ["-", "_", "─"]

  # new lines
  object-curly-newline:
    - warn
    - multiline: true
  newline-per-chained-call:
    - error
    - ignoreChainWithDepth: 3
  no-multiple-empty-lines:
    - warn
    - max: 2

  # Async & Await
  no-await-in-loop: error
  require-atomic-updates: error

  # Functions
  no-empty-function: warn
  array-callback-return:
    - error
    - checkForEach: false
      allowImplicit: true
  no-useless-return: error

  # Parenthesis
  no-extra-parens:
    - warn
    - all
    - returnAssign: false

  # Loops
  no-unmodified-loop-condition: error
  no-unreachable-loop: error

  # Semicolon
  no-extra-semi: warn
  semi-style:
    - error
    - last
  semi:
    - warn
    - always
    - omitLastInOneLineBlock: true

  # Commas
  comma-spacing: warn
  comma-style: warn
  comma-dangle:
    - warn
    - always-multiline
  quotes:
    - warn
    - double
    - avoidEscape: true
      allowTemplateLiterals: true

  # Imports
  no-duplicate-imports: warn
  sort-imports: warn
  dot-notation: error

  # Strings
  no-useless-concat: warn
  no-multi-str: error

  # Numbers
  no-magic-numbers:
    - error
    - ignore: [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 0.1, 0.2, 0.5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 100, 1000, 10000, 1024]
      ignoreArrayIndexes: true
  no-floating-decimal: warn
  no-implicit-coercion: error

  # Regex
  prefer-regex-literals:
    - error
    - disallowRedundantWrapping: true

  # Conditions
  eqeqeq: error
  no-eq-null: error
  no-negated-condition: error
  no-unneeded-ternary: warn
  no-nested-ternary: error
  yoda: warn
  no-else-return:
    - error
    - allowElseIf: true
  no-lonely-if: warn
  no-mixed-operators:
    - error
    - groups:
        - ['%', '**']
        - ['&', '|', ^, "~", <<, '>>', '>>>']
        - [==, '!=', ===, '!==', '>', '>=', <, <=]
        - ['&&', '||']
        - [in, instanceof]
