import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const minified = process.argv[2] === "minified";

esbuild
	.build({
		banner: { js: banner },
		entryPoints: ["src/main.ts"],
		bundle: true,
		external: ["obsidian", "electron", ...builtins],
		format: "cjs",
		target: "es2021",
		logLevel: "info",
		sourcemap: false,
		treeShaking: true,
		minify: minified,
		outfile: "main.js",
	})
	.catch(() => process.exit(1));
